services:
  - type: web
    name: inland-cafe-pos
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: NODE_ENV
        value: production
