services:
  - type: web
    name: inland-cafe-pos
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run server
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: inland-cafe-pos-secret-2024
